export interface LLMSTxtConfig {
  enabled: boolean;
  sections: {
    includePersonalInfo: boolean;
    includeSkills: boolean;
    includeExperience: boolean;
    includeProjects: boolean;
    includeEducation: boolean;
  };
  format: 'markdown' | 'plain' | 'structured';
  maxLength?: number;
  includeTechnicalDetails: boolean;
  includeAchievements: boolean;
}

export interface StructuredDataConfig {
  enabled: boolean;
  schemas: {
    person: boolean;
    organization: boolean;
    webSite: boolean;
    breadcrumbList: boolean;
  };
  includeJobPostings: boolean;
  includeProjects: boolean;
}

export interface SEOConfig {
  enabled: boolean;
  autoGenerateMetaTags: boolean;
  autoGenerateDescriptions: boolean;
  includeOpenGraph: boolean;
  includeTwitterCards: boolean;
  keywords: string[];
  customMetaTags: Record<string, string>;
}

export interface AIAnalyticsConfig {
  enabled: boolean;
  trackUserInteractions: boolean;
  generateInsights: boolean;
  optimizationSuggestions: boolean;
  performanceMetrics: boolean;
}

export interface ContentOptimizationConfig {
  enabled: boolean;
  autoSummarization: boolean;
  keywordExtraction: boolean;
  readabilityAnalysis: boolean;
  contentSuggestions: boolean;
  languageOptimization: boolean;
}

export interface AIOptimizationConfig {
  llmsTxt: LLMSTxtConfig;
  structuredData: StructuredDataConfig;
  seo: SEOConfig;
  analytics: AIAnalyticsConfig;
  contentOptimization: ContentOptimizationConfig;
  aiProvider: {
    name: 'openai' | 'anthropic' | 'google' | 'local' | 'custom';
    apiKey?: string;
    model?: string;
    endpoint?: string;
  };
  caching: {
    enabled: boolean;
    ttl: number;
    storage: 'memory' | 'redis' | 'file';
  };
}

export const defaultAIOptimizationConfig: AIOptimizationConfig = {
  llmsTxt: {
    enabled: true,
    sections: {
      includePersonalInfo: true,
      includeSkills: true,
      includeExperience: true,
      includeProjects: true,
      includeEducation: true,
    },
    format: 'markdown',
    maxLength: 8000,
    includeTechnicalDetails: true,
    includeAchievements: true,
  },
  structuredData: {
    enabled: true,
    schemas: {
      person: true,
      organization: false,
      webSite: true,
      breadcrumbList: true,
    },
    includeJobPostings: false,
    includeProjects: true,
  },
  seo: {
    enabled: true,
    autoGenerateMetaTags: true,
    autoGenerateDescriptions: true,
    includeOpenGraph: true,
    includeTwitterCards: true,
    keywords: [],
    customMetaTags: {},
  },
  analytics: {
    enabled: false,
    trackUserInteractions: false,
    generateInsights: false,
    optimizationSuggestions: false,
    performanceMetrics: false,
  },
  contentOptimization: {
    enabled: true,
    autoSummarization: false,
    keywordExtraction: true,
    readabilityAnalysis: true,
    contentSuggestions: false,
    languageOptimization: false,
  },
  aiProvider: {
    name: 'openai',
    model: 'gpt-3.5-turbo',
  },
  caching: {
    enabled: true,
    ttl: 3600,
    storage: 'memory',
  },
};