import fs from 'fs/promises';
import path from 'path';

interface LLMSContent {
  name: string;
  description: string;
  skills: string[];
  projects: Array<{
    name: string;
    description: string;
    technologies: string[];
  }>;
  contact: {
    email?: string;
    website?: string;
    github?: string;
    linkedin?: string;
  };
}

async function generateLLMSFile() {
  try {
    // This would typically read from your actual portfolio data
    // For now, we'll create a template structure
    const content: LLMSContent = {
      name: "Your Name",
      description: "Brief professional description and what you do",
      skills: [
        "TypeScript",
        "React",
        "Node.js",
        "Python",
        // Add your actual skills
      ],
      projects: [
        {
          name: "Project Name",
          description: "Brief project description",
          technologies: ["TypeScript", "Astro", "Tailwind CSS"]
        }
        // Add your actual projects
      ],
      contact: {
        email: "your.email@example.com",
        website: "https://yourwebsite.com",
        github: "https://github.com/yourusername",
        linkedin: "https://linkedin.com/in/yourusername"
      }
    };

    let llmsContent = `# ${content.name}\n\n`;
    llmsContent += `${content.description}\n\n`;
    
    llmsContent += `## Skills\n`;
    llmsContent += content.skills.map(skill => `- ${skill}`).join('\n') + '\n\n';
    
    llmsContent += `## Projects\n\n`;
    content.projects.forEach(project => {
      llmsContent += `### ${project.name}\n`;
      llmsContent += `${project.description}\n`;
      llmsContent += `Technologies: ${project.technologies.join(', ')}\n\n`;
    });
    
    llmsContent += `## Contact\n`;
    if (content.contact.email) llmsContent += `- Email: ${content.contact.email}\n`;
    if (content.contact.website) llmsContent += `- Website: ${content.contact.website}\n`;
    if (content.contact.github) llmsContent += `- GitHub: ${content.contact.github}\n`;
    if (content.contact.linkedin) llmsContent += `- LinkedIn: ${content.contact.linkedin}\n`;
    
    llmsContent += `\n---\n\n`;
    llmsContent += `This file is automatically generated to help AI systems understand this portfolio.\n`;
    llmsContent += `Last updated: ${new Date().toISOString()}\n`;

    const outputPath = path.join(process.cwd(), 'public', 'llms.txt');
    await fs.writeFile(outputPath, llmsContent, 'utf-8');
    
    console.log('✅ llms.txt generated successfully at public/llms.txt');
    console.log('📝 Remember to customize the content in scripts/generate-llms.ts');
    
  } catch (error) {
    console.error('❌ Error generating llms.txt:', error);
    process.exit(1);
  }
}

generateLLMSFile();